### ISSUE TITLE
Increment operator doesn't seem to wotk

### ISSUE THREAD

**Issue by SimoTod** [nyariv/SandboxJS#2]
Hi, I've been playing with your library for a bit and I like it.
The size is quite small compared to other parsers. Is it because it only support a subset of js instructions?

For example, a simple instruction like 'foo++' seems to fail, but I would expect it to work since it's quite a basic one.

```javascript
const s = new Sandbox();
s.compile('var foo = 0; foo++;'); // OK
s.compile('var foo; foo++;') // Fail
```

Thanks.

P.s. I'm posting here so we won't pollute the thread in the Alpine repo.

**Comment by nyariv** [comment]
Yeah it's a much smaller subset, designed for angular markup type expressions.

Technically the failed code should not work natively either. Var without setting a value is undefined, which you can't increment.

Its best to compare failures with eval.

**Comment by nyariv** [comment]
my bad, seems there is a bug. will add more test to cover everything.

**Comment by SimoTod** [comment]
Yeah, sorry. I noticed the var thing, and I did initialise it to 0 but I didn't write the example correctly.

Alpine with your library is just 10 kb so we may be able to convince Caleb but I need to configure it so all tests passes. 

50% of the demo page works already which is more than i was expecting.

**Comment by nyariv** [comment]
thankfully these fixes are easy, will probably be done in a few hours.

**Comment by SimoTod** [comment]
No rush, thanks for looking into it.

**Comment by nyariv** [comment]
k, pushed a bunch of fixes. will need more fuzzing type of tests down the line. Let me know if this now looks better on your end.

**Comment by nyariv** [comment]
There is one caveat I am not sure if it should be tackled with var/let/const. Right now only `let` will export the variable to the supplied scope, because const would require doing some weird and unexpected things a scope object, and there is no difference between var and let in the context of dom expressions, so for now `const` in `var` are only supported superficially within the current scope, but only `let` will export the variable, for simplicity's sake.

**Comment by SimoTod** [comment]
yep, it works now. Much appreciated.
